### ISSUE TITLE
Creating Users

### ISSUE THREAD

**Issue by HeIp** [mathbotics/app#18]
Some of you will find that the seed command is not working.
This is due to a module that doesn't exist - tsnd
`yarn seed src/seeders/AdminSeeder.ts`
Will not work/create users due to this missing package.

hopefully @andres-valdes  or @david-castaneda can help us.

**Comment by david-castaneda** [comment]
https://github.com/mathbotics/app/blob/master/backend/src/seeders/AdminSeeder.ts

**Comment by HeIp** [comment]
> https://github.com/mathbotics/app/blob/master/backend/src/seeders/AdminSeeder.ts

"seed": "DATABASE_URL='postgres://postgres:password@localhost:5432/postgres' ./node_modules/.bin/tsnd --no-notify --transpileOnly"
I believe it's due to the seed command in package.json using `node_modules/.bin/tsnd` which doesn't exist upon installation

**Comment by david-castaneda** [comment]
![image](https://user-images.githubusercontent.com/21694364/91911767-c77bc300-ec7f-11ea-80c0-1ad3a486bfcd.png)
 
Can't really run the backend... @andres-valdes might have some insight

**Comment by david-castaneda** [comment]
![image](https://user-images.githubusercontent.com/21694364/91912306-d3b45000-ec80-11ea-85cb-29d33ed5a62b.png)

Cant really get past this... @andres-valdes any idea?

Things i tried:
- Upgrade Prisma
- remove `--transpileOnly` flag from `dev` command in `package.json`
- install [ts-node-dev](https://www.npmjs.com/package/ts-node-dev) to see if those `tsnd` errors subdue

**Comment by HeIp** [comment]
![image](https://user-images.githubusercontent.com/31706214/91926437-433c3680-eca5-11ea-8aa3-2440f07bdeb0.png)
@david-castaneda this is something I manage to end up in

**Comment by andres-valdes** [comment]
@primsa/client is the generated portion.

Run yarn gen.

**Comment by HeIp** [comment]
![image](https://user-images.githubusercontent.com/31706214/91987875-98576700-ecfc-11ea-9d02-40e9c619af09.png)
@andres-valdes

**Comment by HeIp** [comment]
Possibly fixed the error above by modifying schema.prisma as shown:
![image](https://user-images.githubusercontent.com/31706214/92019473-ac16c380-ed24-11ea-9c29-ac06fc68b78c.png)
and removed --transpileOnly argument from "gen:nexus" in package .json
now results in :
![image](https://user-images.githubusercontent.com/31706214/92019606-e2544300-ed24-11ea-9ebf-c305decb0b65.png)

**Comment by HeIp** [comment]
Resolved all these problems in the [bugs/windows/pattern-error](https://github.com/mathbotics/app/tree/bugs/windows/pattern-error) branch. Problem is seed gives a false positive of correctly executing but doesn't add the admin user to the postgresql db

**Comment by HeIp** [comment]
Fixed
